<?php

/**
 * @file
 * Contains unt_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unt_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unt_events module.
    case 'help.page.unt_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pulls articles from the campus news site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function unt_news_theme($existing, $type, $theme, $path) {
  return [
    'unt_news_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'unt_news_story' => [
      'variables' => [
        'headline' => NULL,
        'image' => NULL,
        'department' => NULL,
        'content' => NULL,
      ],
      'render element' => 'children',
    ]
  ];
}
